spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka
    fetch-registry: true
    register-with-eureka: true


jwt:
  secretKey: 1MCd9Le3ps1RUgYu42uYDCpBfq957N6P
  secretRefreshKey: 24CAek3pcGJRAB6ZjNULjNV9u5dXLuQ2
  valid-mins: 40m
  valid-mins-ref-token: 120m